version: '3.5'
services:
    php:
        image: php:7.4-fpm
        ports:
            - 9000:9000
        volumes:
            - ./src:/var/www/html
        links:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: ea_test
            MYSQL_USER: root
            MYSQL_PASSWORD:
        ports:
            - 3307:3306
        expose:
            - 3306
volumes:
    db_data: {}
