services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        ports:
            - "9007:9007"
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        container_name: app
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        volumes:
            -  ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ea_test
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306
        container_name: mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
